#!/usr/bin/env bash

# This hack can be removed if https://github.com/docker-library/docker/pull/444 gets merged.

# Remove docker pidfile if it exists to ensure Docker can start up after a bad shutdown
pidfile="~/umbrel/app-data/portainer/data/docker/docker.pid"
if [[ -f "${pidfile}" ]]
then
    rm -f "${pidfile}"
fi
